function $(id){
  return document.getElementById(id);
}

const csvData = `0,chr(int())
1,chr(not())
2,chr(len(str(dict())))
3,chr(len(hex(int())))
4,chr(len(str(not())))
5,chr(len(str(set())))
6,chr(len(str(complex(not()))))
7,chr(len(repr(str(set()))))
8,chr(len(bin(ord(str(int())))))
9,chr(len(repr(repr(chr(int())))))
10,min(str(credits))
11,chr(len(str(range(int()))))
12,chr(len(set(str(type(bytes())))))
13,chr(len(str(type(int()))))
14,chr(len(str(type(not()))))
15,chr(len(str(type(float()))))
16,chr(len(str(type(object()))))
17,chr(len(str(type(complex()))))
18,chr(len(str(type(reversed(str())))))
19,chr(len(repr(str(type(complex())))))
20,chr(len(str(set(str(not())))))
21,chr(len(str(set(str(not()))))+int(not()))
22,chr(len(str(type(iter(set())))))
23,chr(len(str(type(iter(set()))))+int(not()))
24,chr(len(str(type(iter(bytes())))))
25,chr(len(str(set(str(set())))))
26,chr(len(str(type(iter(dict())))))
27,chr(len(str(type(iter(dict()))))+int(not()))
28,chr(len(str(type(iter(str())))))
29,chr(max(range(len(str(zip())))))
30,chr(len(str(zip())))
31,chr(len(str(zip()))+int(not()))
32,min(str(range(int())))
33,chr(ord(min(str(range(not()))))+int(not()))
34,min(repr(repr(str())))
35,chr(len(str(reversed(str()))))
36,chr(len(str(reversed(str())))+int(not()))
37,chr(len(str(reversed(str())))+int(not())+int(not()))
38,chr(len(str(reversed(str())))+int(not())+int(not())+int(not()))
39,max(repr(str()))
40,min(str(set()))
41,max(str(tuple()))
42,chr(ord(next(reversed(str(range(not())))))+int(not()))
43,chr(ord(next(reversed(str(range(not())))))+int(not())+int(not()))
44,max(str(tuple(repr(str()))))
45,chr(sum(range(int(str(int(not()))+str(int())))))
46,min(str(float()))
47,chr(max(range(ord(str(int())))))
48,str(int())
49,str(int(not()))
50,str(len(str(dict())))
51,str(len(hex(int())))
52,str(len(str(not())))
53,str(len(str(set())))
54,str(len(str(complex(not()))))
55,max(str(ord(max(str(not())))))
56,max(str(ord(str(int()))))
57,max(str(ord(str(int(not())))))
58,chr(ord(max(str(ord(str(int(not()))))))+int(not()))
59,chr(ord(max(str(ord(str(int(not()))))))+int(not())+int(not()))
60,next(iter(str(object())))
61,chr(ord(next(iter(str(object()))))+int(not()))
62,next(reversed(str(object())))
63,chr(ord(next(reversed(str(object()))))+int(not()))
64,chr(ord(min(str(range(not()))))+ord(min(str(range(not())))))
65,chr(ord(next(reversed(str(object()))))+int(not())+int(not())+int(not()))
66,chr(ord(min(str(range(not()))))+int(not())+ord(min(str(range(not()))))+int(not()))
67,next(iter(str(copyright)))
68,chr(ord(next(iter(str(copyright))))+int(not()))
69,chr(ord(next(iter(str(copyright))))+int(not())+int(not()))
70,min(str(not(not())))
71,chr(ord(next(iter(str(not(not())))))+int(not()))
72,chr(ord(min(str(range(not()))))+ord(min(str(set()))))
73,chr(ord(min(str(range(not()))))+ord(min(str(set())))+int(not()))
74,chr(ord(min(str(range(not()))))+ord(min(str(set())))+int(not())+int(not()))
75,chr(ord(min(str(range(not()))))+ord(min(str(set())))+int(not())+int(not())+int(not()))
76,chr(ord(min(str(range(not()))))+ord(min(str(set())))+int(not())+int(not())+int(not())+int(not()))
77,chr(ord(min(str(range(not()))))+ord(min(str(set())))+int(next(reversed(hex(ord(max(str(not()))))))))
78,chr(ord(min(str(bytes())))+ord(min(str(bytes()))))
79,chr(ord(min(str(bytes())))+ord(min(str(bytes())))+int(not()))
80,chr(ord(min(str(set())))+ord(min(str(set()))))
81,chr(ord(min(str(set())))+ord(min(str(set())))+int(not()))
82,chr(ord(next(reversed(str(range(not())))))+ord(next(reversed(str(range(not()))))))
83,chr(max(range(ord(min(str(not()))))))
84,min(str(not()))
85,chr(ord(min(str(not())))+int(not()))
86,chr(ord(min(str(not())))+int(not())+int(not()))
87,chr(ord(min(str(not())))+int(not())+int(not())+int(not()))
88,chr(ord(min(str(not())))+int(not())+int(not())+int(not())+int(not()))
89,chr(ord(min(str(not())))+int(next(reversed(hex(ord(max(str(not()))))))))
90,chr(ord(min(str(not())))+int(next(reversed(hex(ord(max(str(vars))))))))
91,chr(int(not())+ord(min(str(not())))+int(next(reversed(hex(ord(max(str(vars))))))))
92,max(repr(repr(repr(str()))))
93,chr(ord(min(str(float())))+ord(min(str(float())))+int(not()))
94,chr(ord(min(str(float())))+int(not())+ord(min(str(float())))+int(not()))
95,min(max(vars()))
96,chr(ord(min(min(locals())))+int(not()))
97,next(reversed(hex(ord(max(str(complex()))))))
98,max(bin(int()))
99,next(reversed(hex(ord(next(iter(str(object())))))))
100,next(reversed(hex(ord(max(str(dict()))))))
101,next(reversed(str(not())))
102,next(iter(str(frozenset())))
103,chr(ord(next(iter(str(frozenset()))))+int(not()))
104,chr(ord(str(int()))+ord(next(reversed(hex(ord(max(str(object()))))))))
105,chr(ord(str(int()))+ord(next(reversed(hex(ord(max(str(bytearray()))))))))
106,max(str(complex()))
107,chr(ord(max(str(complex())))+int(not()))
108,chr(ord(str(int()))+ord(next(iter(str(object())))))
109,chr(ord(str(int(not())))+ord(next(iter(str(object())))))
110,chr(int(str(int(not()))+str(int(not()))+str(int())))
111,max(oct(int()))
112,chr(ord(max(oct(int())))+int(not()))
113,chr(ord(max(oct(int())))+int(not())+int(not()))
114,max(str(range(int())))
115,max(str(not(not())))
116,max(str(set()))
117,max(str(not()))
118,max(str(type(reversed(str()))))
119,max(str(pow))
120,max(hex(int()))
121,max(str(type(bytes())))
122,max(str(zip))
123,min(str(dict()))
124,chr(ord(min(str(dict())))+int(not()))
125,max(str(dict()))
126,chr(ord(max(str(dict())))+int(not()))`;

const astrixData = `64,chr(ord(min(str(range(not()))))*(int(not())+int(not())))`;

const periodData = `65,next(reversed(hex(ord(max(str(complex())))))).upper()
66,max(str(bytes())).upper()
69,next(reversed(str(not()))).upper()
74,max(str(complex())).upper()
75,chr(ord(max(str(complex())))+int(not())).upper()
76,chr(ord(str(int()))+ord(next(iter(str(object()))))).upper()
77,chr(ord(str(int(not())))+ord(next(iter(str(object()))))).upper()
79,max(oct(int())).upper()
82,next(iter(str(range(not())))).upper()
83,max(str(not(not()))).upper()
85,max(str(not())).upper()
86,max(str(vars)).upper()
87,max(str(pow)).upper()
88,max(str(object())).upper()
89,max(str(credits)).upper()
90,max(str(zip)).upper()
99,next(iter(str(copyright))).lower()
104,chr(ord(min(str(range(not()))))+ord(min(str(set())))).lower()
105,chr(ord(min(str(range(not()))))+ord(min(str(set())))+int(not())).lower()`;

function mapCharacters(csvData) {
  const charMap = {};
  const rows = csvData.trim().split('\n');
  rows.slice(1).forEach(row => {
    const [char, func] = row.split(',');
    if (char && func) {
      charMap[char] = func;
    }
  });
  return charMap
}

const charMapPeriod = mapCharacters(periodData);
const charMapAstrix = mapCharacters(astrixData);

function replaceAndJoin(input) {
  const asciiValues = Array.from(input, char => char.charCodeAt(0));
  let map = mapCharacters(csvData);
  if($('period').checked) Object.assign(map, charMapPeriod);
  if($('astrix').checked) Object.assign(map, charMapAstrix);
  let out = asciiValues.map(char => map[char] || `  <COULDNT FIND ${char}>  `).join('+');
  return $('eval').checked ? `exec(${out})` : out;
}
